name: Build and Test Frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install
        working-directory: ./client

      - name: Ejecutar lint
        run: npm run lint
        working-directory: ./client

      - name: Ejecutar pruebas
        run: npm test -- --watchAll=false
        working-directory: ./client

      - name: Ejecutar build
        run: npm run build
        working-directory: ./client
