name: Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      CI: false

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install server dependencies
      run: |
        cd server
        npm ci --legacy-peer-deps

    - name: Install client dependencies
      run: |
        cd client
        npm ci --legacy-peer-deps

    - name: Build client
      run: |
        cd client
        npm run build

    # Deploy frontend to Azure Static Web Apps
    - name: Deploy frontend to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "client"
        output_location: "dist"
        skip_app_build: true
        api_location: "server"
        production_branch: "main"

    # Deploy backend to Azure App Service
    - name: Deploy backend to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './server'
